### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by alexplisov** [steam-items/steam-user-inventory#1]
Hello! I've tried to pull gifts from user's inventory.
In some reason it display this error:
`(node:16359) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'forEach' of undefined
(node:16359) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I've tried to comment forEach section in index.js and console.log'ed res.body:
`{
	"success":true,
	"rgInventory":{
		"922506184369981039":{
			"id":"922506184369981039",
			"classid":"1254492673",
			"instanceid":"2070301907",
			"amount":"1",			
			"pos":1
		}
	},
	"rgCurrency":[],
	"rgDescriptions":{"1254492673_2070301907":{
		"appid":"753",
		"classid":"1254492673",
		"instanceid":"2070301907",
		"icon_url":"U8721VM9p9C2v1o6cKJ4qEnGqnE7IoTQgZI-VTdwyTBeimAcIowbqB-harb00cJ0fNdiCJoFB3O541FNc9ZPYXYjjL7UqfFEwOtgZKcs0eWlClqzSJn6",
		"icon_url_large":"U8721VM9p9C2v1o6cKJ4qEnGqnE7IoTQgZI-VTdwyTBeimAcIowbqB-harb00cJ0fNdiA54UEGOnqGQPJ9hDZHA50feEo7RMyO_GQNzkkA",
		"icon_drag_url":"",
		"name":"BEEP",
		"market_name":"",
		"name_color":"",
		"background_color":"",
		"type":"Gift",
		"tradable":0,
		"marketable":0,
		"commodity":0,
		"cache_expiration":"2017-01-02T00:00:00Z",
		"fraudwarnings":["This is a restricted gift which can only be redeemed in these countries: Armenia, Azerbaijan, Belarus, Georgia, Kyrgyzstan, Kazakhstan, Moldova, Republic of, Tajikistan, Turkmenistan, Uzbekistan, Ukraine, Russian Federation"],
		"descriptions":[{"value":"A combination of Yoshi\u2019s Island-style platforming with a gravity gun right out of Half-Life, BEEP is an amazing physics-platformer. Despite its friendly art style, this is a hardcore platformer in the truest sense."}],
		"actions":[{"name":"View in store","link":"http:\/\/store.steampowered.com\/app\/104200\/"}]
	}},
	"more":false,
	"more_start":false
}`

Sorry for English!

**Comment by alexplisov** [comment]
Just found a solution.
The problem was forEach that sets tags.
After I commented it, everything works fine!

**Comment by danielhusar** [comment]
Thank you, I try to fix it over christmas :)
