### ISSUE TITLE
How check is status to many requests?

### ISSUE THREAD

**Issue by slowas** [steam-items/steam-user-inventory#3]
Hello, How check is request status is Too many requests? Becouse I'am don't  see status or somenthing else.. Thx for answer

**Comment by danielhusar** [comment]
Hey, this is using private steam apis so I don't really know if you can do that.

**Comment by Zendrex** [comment]
I'm not sure what "private" api you are using here.
https://github.com/mdm-skins/steam-user-inventory/blob/bfb9ddf04fcbf643cce4a88edf4b8900e3043ad6/index.js#L14
https://github.com/mdm-skins/steam-user-inventory/blob/bfb9ddf04fcbf643cce4a88edf4b8900e3043ad6/index.js#L16

**Comment by danielhusar** [comment]
Private apis refer to not be used by third party apps. Steam doesn’t document those anywhere so they are private.

**Comment by Zendrex** [comment]
Steam gives information on request limits here: http://steamcommunity.com/dev/apiterms

**Comment by danielhusar** [comment]
Yes, but those market endpoints are not part of their official api.
